[package]
name = "compression-service"
version = "0.1.0"
authors = ["Michael Mogenson <michael.mogenson@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures = "0.3"
tokio-util = { version = "0.2", features = ["full"] }
tokio = { version = "0.2", features = ["full"] }
